### ISSUE TITLE
404 page on /my-account/new-warranty-request/

### ISSUE THREAD

**Issue by vdcMartijn** [chilidevs/woocommerce-return-warranty-management#8]
Hi, 

After installing the plug-in, the page seems to be completely missing. It's not in the Pages tab of Wordpress either. Both: 
/my-account/new-warranty-request/
/my-account/warranty-requests/ 
are giving a 404 page. 

The website is in maintenance mode, so sharing the URL won't get you far. 
Wordpress version: 5.5.1
Theme: Flatsome 13.12.2
Woocommerce: 4.4.1
Woocommerce Return Warranty Management: 1.1.10

![image](https://user-images.githubusercontent.com/70850504/92328273-dab3d780-f05f-11ea-8f08-fa89f2fa3312.png)

**Comment by vdcMartijn** [comment]
This can be closed, was probably a cache issue, as it got magically solved the day after

**Comment by chilidevs** [comment]
Fixed #60406ac
